//! OpenAPI Documentation
//!
//! Swagger UI and OpenAPI specification endpoints.

use axum::Router;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa::{Modify, OpenApi};
use utoipa_swagger_ui::SwaggerUi;

use crate::api::http::routes::admin::{
    // Database operations
    CopyKeyRequest, CopyKeyResponse, MoveKeyRequest, MoveKeyResponse,
    SwapDbRequest, SwapDbResponse, DbSizeResponse, FlushDbRequest,
    // Server info
    LastSaveResponse,
    // Memory operations
    MemoryUsageRequest, MemoryDoctorResponse, MemoryPurgeResponse,
    // Config operations
    ConfigGetRequest, ConfigGetResponse, ConfigSetRequest, ConfigSetResponse,
    ConfigRewriteResponse, ConfigResetStatResponse,
    // Persistence operations
    SaveResponse,
    // Client operations
    ClientListResponse, ClientKillRequest, ClientKillResponse,
    ClientPauseRequest, ClientPauseResponse, ClientUnpauseResponse,
    ClientSetNameRequest, ClientSetNameResponse, ClientGetNameResponse, ClientIdResponse,
    // Monitoring operations
    SlowlogGetRequest, SlowlogGetResponse, SlowlogLenResponse, SlowlogResetResponse,
    LatencyLatestResponse, LatencyHistoryRequest, LatencyHistoryResponse,
    LatencyDoctorResponse, LatencyResetRequest, LatencyResetResponse,
    // ACL operations
    AclListResponse, AclUsersResponse, AclWhoamiResponse,
    AclCatRequest, AclCatResponse, AclGenPassRequest, AclGenPassResponse,
    AclLogRequest, AclLogResponse,
};
// Domain entities used directly in API responses
use crate::domain::entities::{
    ServerInfo, ServerTime, MemoryStats, MemoryUsage,
    ClientInfo, SlowlogEntry, LatencyEvent, AclLogEntry,
    FlushResult, BgSaveResult, BgRewriteAofResult,
};
use crate::api::http::schemas::strings::{
    AppendRequest, AppendResponse, GetDelResponse, GetExParams, GetRangeParams,
    GetRangeResponse, IncrementRequest, IncrementResponse, MGetRequest, MGetResponse,
    MSetRequest, MSetResponse, SetRangeRequest, SetRangeResponse, SetStringRequest,
    SetStringResponse, StrLenResponse,
};
use crate::api::http::schemas::common::{KeyInfo, PaginationParams, TtlInfo};
use crate::api::http::schemas::keys::{
    ScanParams, DeleteKeysRequest, DeleteKeysResponse, ExistsRequest, ExistsResponse,
    ExpireRequest, ExpireResponse, TtlResponse, PersistResponse, TypeResponse,
    RenameRequest, RenameResponse, CopyRequest, CopyResponse, ScanResponse,
    KeysParams, KeysResponse, TouchRequest, TouchResponse, RandomKeyResponse,
    DumpResponse, RestoreRequest, RestoreResponse, ObjectInfoResponse, KeyInfoResponse,
};
use crate::api::http::schemas::hashes::{
    GetMultipleFieldsRequest, HashFieldEntry, HashIncrFloatRequest, HashIncrRequest,
    HashRandomFieldResponse, HashScanResponse, RandomFieldQuery, ScanHashQuery,
    SetHashNxRequest, SetHashRequest,
};
use crate::api::http::schemas::lists::{
    BlockingMoveRequest, BlockingPopRequest, BlockingPopResponse,
    InsertPositionParam, ListDirectionParam, ListIndexQuery, ListIndexResponse,
    ListInsertRequest, ListInsertResponse, ListLengthResponse, ListMoveRequest,
    ListMoveResponse, ListPopRequest, ListPopResponse, ListPosQuery, ListPosResponse,
    ListPushRequest, ListPushResponse, ListRangeQuery, ListRemoveRequest,
    ListRemoveResponse, ListSetRequest, ListTrimRequest,
};
use crate::api::http::schemas::sets::{
    SetAddRequest, SetAddResponse, SetAlgebraRequest, SetAlgebraResponse,
    SetAlgebraStoreRequest, SetAlgebraStoreResponse, SetCardResponse,
    SetInterCardRequest, SetInterCardResponse, SetIsMemberRequest, SetIsMemberResponse,
    SetMIsMemberRequest, SetMIsMemberResponse, SetMembersResponse, SetMoveRequest,
    SetMoveResponse, SetPopRequest, SetPopResponse, SetRandMemberQuery,
    SetRandMemberResponse, SetRemoveRequest, SetRemoveResponse, SetScanQuery, SetScanResponse,
};
use crate::api::http::schemas::sorted_sets::{
    LexRangeDto, ScoreRangeDto, ScoredMemberDto, ZAddIncrRequest, ZAddIncrResponse,
    ZAddOptionsDto, ZAddRequest, ZAddResponse, ZAggregateDto, ZBMPopRequest, ZBPopRequest,
    ZBPopResponse, ZCardResponse, ZCountRequest, ZCountResponse, ZDiffRequest,
    ZDiffStoreRequest, ZIncrByRequest, ZIncrByResponse, ZInterCardRequest, ZInterCardResponse,
    ZLexCountRequest, ZMPopRequest, ZMPopResponse, ZMScoreRequest, ZMScoreResponse,
    ZPopQuery, ZPopResponse, ZRandMemberQuery, ZRandMemberResponse, ZRangeByLexRequest,
    ZRangeByLexResponse, ZRangeByScoreRequest, ZRangeQuery, ZRangeResponse,
    ZRangeStoreRequest, ZRangeStoreResponse, ZRankResponse, ZRemRangeByLexRequest,
    ZRemRangeByRankRequest, ZRemRangeByScoreRequest, ZRemRangeResponse, ZRemRequest,
    ZRemResponse, ZScanQuery, ZScanResponse, ZScoreResponse, ZSetAlgebraOptionsDto,
    ZSetAlgebraRequest, ZSetAlgebraResponse, ZSetAlgebraStoreRequest, ZSetAlgebraStoreResponse,
};
use crate::api::http::schemas::streams::{
    ConsumerCreateRequest, ConsumerGroupCreateRequest, ConsumerGroupCreateResponse,
    ConsumerGroupSetIdRequest, ConsumerOperationResponse, PendingQuery, StreamAckRequest,
    StreamAckResponse, StreamAddRequest, StreamAddResponse, StreamAutoClaimRequest,
    StreamClaimRequest, StreamDeleteRequest, StreamDeleteResponse, StreamEntriesResponse,
    StreamGroupSubscribeQuery, StreamIdPair, StreamInfoQuery, StreamLengthResponse,
    StreamRangeQuery, StreamReadBlockingRequest, StreamReadGroupBlockingRequest,
    StreamReadGroupRequest, StreamReadRequest, StreamSetIdRequest, StreamSubscribeQuery,
    StreamTrimRequest, StreamTrimResponse, TrimStrategyParam,
};
use crate::api::http::schemas::json::{
    JsonArrAppendRequest, JsonArrAppendResponse, JsonArrIndexRequest, JsonArrIndexResponse,
    JsonArrInsertRequest, JsonArrInsertResponse, JsonArrLenParams, JsonArrLenResponse,
    JsonArrPopRequest, JsonArrPopResponse, JsonArrTrimRequest, JsonArrTrimResponse,
    JsonClearParams, JsonClearResponse, JsonDebugMemoryParams, JsonDebugMemoryResponse,
    JsonDelParams, JsonDelResponse, JsonGetParams, JsonGetResponse, JsonMGetRequest,
    JsonMGetItem, JsonMGetResponse, JsonMSetItemRequest, JsonMSetRequest, JsonNumIncrByRequest,
    JsonNumMultByRequest, JsonNumResponse, JsonObjKeysParams, JsonObjKeysResponse, JsonObjLenParams,
    JsonObjLenResponse, JsonRespParams, JsonRespResponse, JsonSetRequest, JsonSetResponse,
    JsonStrAppendRequest, JsonStrAppendResponse, JsonStrLenParams, JsonStrLenResponse,
    JsonToggleParams, JsonToggleResponse, JsonTypeParams, JsonTypeResponse,
};
use crate::domain::entities::{
    AutoClaimResult, ClaimResult, ConsumerGroupInfo, ConsumerInfo, PendingEntry, PendingSummary,
    StreamEntry, StreamInfo, StreamReadResult, StringValue,
};
use crate::domain::errors::{ErrorDetail, ErrorResponse};
use crate::infrastructure::redis::capabilities::{
    FeatureCapabilities, ModuleCapabilities, RedisCapabilities,
};
use crate::infrastructure::redis::connection::PoolStats;
use crate::shared::app_state::AppState;

/// OpenAPI documentation for the Redis Caching Service
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Redis Caching Service API",
        version = "0.1.0",
        description = "A high-performance Redis caching service with comprehensive Redis operations through a clean REST API",
        license(name = "MIT"),
        contact(name = "API Support")
    ),
    servers(
        (url = "/", description = "Local server")
    ),
    tags(
        (name = "Health", description = "Health check endpoints"),
        (name = "Keys", description = "Redis key management operations (DELETE, EXISTS, EXPIRE, TTL, RENAME, COPY, SCAN, etc.)"),
        (name = "Strings", description = "Redis string operations (GET, SET, MGET, MSET, INCR, etc.)"),
        (name = "Hashes", description = "Redis hash operations (HGET, HSET, HMGET, HGETALL, HINCRBY, etc.)"),
        (name = "Lists", description = "Redis list operations (LPUSH, RPUSH, LPOP, RPOP, LRANGE, LLEN, LINDEX, LINSERT, BLPOP, BRPOP, etc.)"),
        (name = "Sets", description = "Redis set operations (SADD, SREM, SMEMBERS, SISMEMBER, SCARD, SINTER, SUNION, SDIFF, SPOP, SRANDMEMBER, etc.)"),
        (name = "Sorted Sets", description = "Redis sorted set operations (ZADD, ZREM, ZSCORE, ZRANK, ZRANGE, ZCOUNT, ZPOPMIN, ZPOPMAX, BZPOPMIN, BZPOPMAX, ZUNION, ZINTER, ZDIFF, ZSCAN, etc.)"),
        (name = "Streams", description = "Redis stream operations (XADD, XREAD, XRANGE, XLEN, XTRIM, consumer groups, etc.)"),
        (name = "Streams (Admin)", description = "Redis stream admin operations (XGROUP CREATE/DESTROY, XSETID, consumer management)"),
        (name = "JSON", description = "RedisJSON operations (JSON.SET, JSON.GET, JSON.DEL, JSON.MGET, array operations, object operations, numeric operations, etc.) - requires RedisJSON module"),
        (name = "Admin", description = "Administrative endpoints (pool stats, capabilities, server info, database ops, config, persistence, client management, monitoring, ACL)")
    ),
    paths(
        // Health endpoints
        crate::api::http::routes::health::health,
        crate::api::http::routes::health::readiness,
        crate::api::http::routes::health::liveness,
        // Key endpoints
        crate::api::http::routes::keys::delete_keys,
        crate::api::http::routes::keys::exists_keys,
        crate::api::http::routes::keys::touch_keys,
        crate::api::http::routes::keys::scan_keys,
        crate::api::http::routes::keys::list_keys,
        crate::api::http::routes::keys::random_key,
        crate::api::http::routes::keys::get_key_info,
        crate::api::http::routes::keys::delete_single_key,
        crate::api::http::routes::keys::get_ttl,
        crate::api::http::routes::keys::set_expire,
        crate::api::http::routes::keys::persist_key,
        crate::api::http::routes::keys::get_type,
        crate::api::http::routes::keys::rename_key,
        crate::api::http::routes::keys::copy_key,
        crate::api::http::routes::keys::dump_key,
        crate::api::http::routes::keys::restore_key,
        crate::api::http::routes::keys::get_object_info,
        // String endpoints
        crate::api::http::routes::strings::get_string,
        crate::api::http::routes::strings::set_string,
        crate::api::http::routes::strings::get_del_string,
        crate::api::http::routes::strings::mget_strings,
        crate::api::http::routes::strings::mset_strings,
        crate::api::http::routes::strings::incr_string,
        crate::api::http::routes::strings::decr_string,
        crate::api::http::routes::strings::append_string,
        crate::api::http::routes::strings::strlen_string,
        crate::api::http::routes::strings::get_range,
        crate::api::http::routes::strings::set_range,
        crate::api::http::routes::strings::get_ex_string,
        // Hash endpoints
        crate::api::http::routes::hashes::hget,
        crate::api::http::routes::hashes::hset,
        crate::api::http::routes::hashes::hset_nx,
        crate::api::http::routes::hashes::hgetall,
        crate::api::http::routes::hashes::hmget,
        crate::api::http::routes::hashes::hdel,
        crate::api::http::routes::hashes::hexists,
        crate::api::http::routes::hashes::hkeys,
        crate::api::http::routes::hashes::hvals,
        crate::api::http::routes::hashes::hlen,
        crate::api::http::routes::hashes::hincr_by,
        crate::api::http::routes::hashes::hincr_by_float,
        crate::api::http::routes::hashes::hstr_len,
        crate::api::http::routes::hashes::hrand_field,
        crate::api::http::routes::hashes::hscan,
        // List endpoints
        crate::api::http::routes::lists::lpush,
        crate::api::http::routes::lists::rpush,
        crate::api::http::routes::lists::lpush_x,
        crate::api::http::routes::lists::rpush_x,
        crate::api::http::routes::lists::lpop,
        crate::api::http::routes::lists::rpop,
        crate::api::http::routes::lists::lrange,
        crate::api::http::routes::lists::llen,
        crate::api::http::routes::lists::lindex,
        crate::api::http::routes::lists::lset,
        crate::api::http::routes::lists::linsert,
        crate::api::http::routes::lists::lrem,
        crate::api::http::routes::lists::ltrim,
        crate::api::http::routes::lists::lpos,
        crate::api::http::routes::lists::lmove,
        crate::api::http::routes::lists::rpop_lpush,
        crate::api::http::routes::lists::blpop,
        crate::api::http::routes::lists::brpop,
        crate::api::http::routes::lists::blmove,
        crate::api::http::routes::lists::brpop_lpush,
        // Set endpoints
        crate::api::http::routes::sets::sadd,
        crate::api::http::routes::sets::srem,
        crate::api::http::routes::sets::smembers,
        crate::api::http::routes::sets::sismember,
        crate::api::http::routes::sets::smismember,
        crate::api::http::routes::sets::scard,
        crate::api::http::routes::sets::srandmember,
        crate::api::http::routes::sets::spop,
        crate::api::http::routes::sets::smove,
        crate::api::http::routes::sets::sinter,
        crate::api::http::routes::sets::sinterstore,
        crate::api::http::routes::sets::sintercard,
        crate::api::http::routes::sets::sunion,
        crate::api::http::routes::sets::sunionstore,
        crate::api::http::routes::sets::sdiff,
        crate::api::http::routes::sets::sdiffstore,
        crate::api::http::routes::sets::sscan,
        // Sorted Set endpoints
        crate::api::http::routes::sorted_sets::zadd,
        crate::api::http::routes::sorted_sets::zadd_incr,
        crate::api::http::routes::sorted_sets::zrem,
        crate::api::http::routes::sorted_sets::zscore,
        crate::api::http::routes::sorted_sets::zmscore,
        crate::api::http::routes::sorted_sets::zincrby,
        crate::api::http::routes::sorted_sets::zcard,
        crate::api::http::routes::sorted_sets::zcount,
        crate::api::http::routes::sorted_sets::zlexcount,
        crate::api::http::routes::sorted_sets::zrank,
        crate::api::http::routes::sorted_sets::zrevrank,
        crate::api::http::routes::sorted_sets::zrange,
        crate::api::http::routes::sorted_sets::zrangebyscore,
        crate::api::http::routes::sorted_sets::zrangebylex,
        crate::api::http::routes::sorted_sets::zrangestore,
        crate::api::http::routes::sorted_sets::zremrangebyrank,
        crate::api::http::routes::sorted_sets::zremrangebyscore,
        crate::api::http::routes::sorted_sets::zremrangebylex,
        crate::api::http::routes::sorted_sets::zpopmin,
        crate::api::http::routes::sorted_sets::zpopmax,
        crate::api::http::routes::sorted_sets::bzpopmin,
        crate::api::http::routes::sorted_sets::bzpopmax,
        crate::api::http::routes::sorted_sets::zmpop,
        crate::api::http::routes::sorted_sets::bzmpop,
        crate::api::http::routes::sorted_sets::zrandmember,
        crate::api::http::routes::sorted_sets::zunion,
        crate::api::http::routes::sorted_sets::zunionstore,
        crate::api::http::routes::sorted_sets::zinter,
        crate::api::http::routes::sorted_sets::zinterstore,
        crate::api::http::routes::sorted_sets::zintercard,
        crate::api::http::routes::sorted_sets::zdiff,
        crate::api::http::routes::sorted_sets::zdiffstore,
        crate::api::http::routes::sorted_sets::zscan,
        // Stream endpoints
        crate::api::http::routes::streams::xadd,
        crate::api::http::routes::streams::xlen,
        crate::api::http::routes::streams::xrange,
        crate::api::http::routes::streams::xrevrange,
        crate::api::http::routes::streams::xdel,
        crate::api::http::routes::streams::xtrim,
        crate::api::http::routes::streams::xinfo_stream,
        crate::api::http::routes::streams::xread,
        crate::api::http::routes::streams::xread_blocking,
        crate::api::http::routes::streams::stream_subscribe,
        crate::api::http::routes::streams::xinfo_groups,
        crate::api::http::routes::streams::xinfo_consumers,
        crate::api::http::routes::streams::xreadgroup,
        crate::api::http::routes::streams::xreadgroup_blocking,
        crate::api::http::routes::streams::xack,
        crate::api::http::routes::streams::xpending_summary,
        crate::api::http::routes::streams::xpending,
        crate::api::http::routes::streams::xclaim,
        crate::api::http::routes::streams::xautoclaim,
        crate::api::http::routes::streams::stream_group_subscribe,
        // Stream admin endpoints
        crate::api::http::routes::streams::xgroup_create,
        crate::api::http::routes::streams::xgroup_destroy,
        crate::api::http::routes::streams::xgroup_setid,
        crate::api::http::routes::streams::xgroup_createconsumer,
        crate::api::http::routes::streams::xgroup_delconsumer,
        crate::api::http::routes::streams::xsetid,
        // JSON endpoints (RedisJSON module)
        crate::api::http::routes::json::json_set,
        crate::api::http::routes::json::json_get,
        crate::api::http::routes::json::json_del,
        crate::api::http::routes::json::json_mget,
        crate::api::http::routes::json::json_mset,
        crate::api::http::routes::json::json_type,
        crate::api::http::routes::json::json_str_len,
        crate::api::http::routes::json::json_str_append,
        crate::api::http::routes::json::json_num_incr_by,
        crate::api::http::routes::json::json_num_mult_by,
        crate::api::http::routes::json::json_toggle,
        crate::api::http::routes::json::json_clear,
        crate::api::http::routes::json::json_arr_len,
        crate::api::http::routes::json::json_arr_append,
        crate::api::http::routes::json::json_arr_index,
        crate::api::http::routes::json::json_arr_insert,
        crate::api::http::routes::json::json_arr_pop,
        crate::api::http::routes::json::json_arr_trim,
        crate::api::http::routes::json::json_obj_len,
        crate::api::http::routes::json::json_obj_keys,
        crate::api::http::routes::json::json_debug_memory,
        crate::api::http::routes::json::json_resp,
        // Admin - Public endpoints
        crate::api::http::routes::admin::get_pool_stats,
        crate::api::http::routes::admin::get_capabilities,
        // Admin - Server info
        crate::api::http::routes::admin::get_server_info,
        crate::api::http::routes::admin::get_server_time,
        crate::api::http::routes::admin::get_db_size,
        crate::api::http::routes::admin::get_lastsave,
        // Admin - Memory
        crate::api::http::routes::admin::get_memory_stats,
        crate::api::http::routes::admin::get_memory_usage,
        crate::api::http::routes::admin::memory_doctor,
        crate::api::http::routes::admin::memory_purge,
        // Admin - Database operations
        crate::api::http::routes::admin::flush_db,
        crate::api::http::routes::admin::flush_all,
        crate::api::http::routes::admin::copy_key,
        crate::api::http::routes::admin::move_key,
        crate::api::http::routes::admin::swap_db,
        // Admin - Config
        crate::api::http::routes::admin::config_get,
        crate::api::http::routes::admin::config_set,
        crate::api::http::routes::admin::config_rewrite,
        crate::api::http::routes::admin::config_resetstat,
        // Admin - Persistence
        crate::api::http::routes::admin::save,
        crate::api::http::routes::admin::bgsave,
        crate::api::http::routes::admin::bgrewriteaof,
        // Admin - Client operations
        crate::api::http::routes::admin::client_list,
        crate::api::http::routes::admin::client_kill,
        crate::api::http::routes::admin::client_pause,
        crate::api::http::routes::admin::client_unpause,
        crate::api::http::routes::admin::client_setname,
        crate::api::http::routes::admin::client_getname,
        crate::api::http::routes::admin::client_id,
        // Admin - Slowlog
        crate::api::http::routes::admin::slowlog_get,
        crate::api::http::routes::admin::slowlog_len,
        crate::api::http::routes::admin::slowlog_reset,
        // Admin - Latency
        crate::api::http::routes::admin::latency_latest,
        crate::api::http::routes::admin::latency_history,
        crate::api::http::routes::admin::latency_doctor,
        crate::api::http::routes::admin::latency_reset,
        // Admin - ACL
        crate::api::http::routes::admin::acl_list,
        crate::api::http::routes::admin::acl_users,
        crate::api::http::routes::admin::acl_whoami,
        crate::api::http::routes::admin::acl_cat,
        crate::api::http::routes::admin::acl_genpass,
        crate::api::http::routes::admin::acl_log,
    ),
    components(
        schemas(
            // Common schemas
            ErrorResponse,
            ErrorDetail,
            KeyInfo,
            PaginationParams,
            TtlInfo,
            // Key schemas
            ScanParams,
            DeleteKeysRequest,
            DeleteKeysResponse,
            ExistsRequest,
            ExistsResponse,
            ExpireRequest,
            ExpireResponse,
            TtlResponse,
            PersistResponse,
            TypeResponse,
            RenameRequest,
            RenameResponse,
            CopyRequest,
            CopyResponse,
            ScanResponse,
            KeysParams,
            KeysResponse,
            TouchRequest,
            TouchResponse,
            RandomKeyResponse,
            DumpResponse,
            RestoreRequest,
            RestoreResponse,
            ObjectInfoResponse,
            KeyInfoResponse,
            // String schemas
            StringValue,
            SetStringRequest,
            SetStringResponse,
            GetDelResponse,
            MGetRequest,
            MGetResponse,
            MSetRequest,
            MSetResponse,
            IncrementRequest,
            IncrementResponse,
            AppendRequest,
            AppendResponse,
            StrLenResponse,
            GetRangeParams,
            GetRangeResponse,
            SetRangeRequest,
            SetRangeResponse,
            GetExParams,
            // Hash schemas
            SetHashRequest,
            SetHashNxRequest,
            GetMultipleFieldsRequest,
            HashIncrRequest,
            HashIncrFloatRequest,
            ScanHashQuery,
            RandomFieldQuery,
            HashFieldEntry,
            HashScanResponse,
            HashRandomFieldResponse,
            // List schemas
            ListPushRequest,
            ListPushResponse,
            ListPopRequest,
            ListPopResponse,
            ListRangeQuery,
            ListLengthResponse,
            ListIndexQuery,
            ListIndexResponse,
            ListSetRequest,
            ListInsertRequest,
            ListInsertResponse,
            InsertPositionParam,
            ListRemoveRequest,
            ListRemoveResponse,
            ListTrimRequest,
            ListPosQuery,
            ListPosResponse,
            ListDirectionParam,
            ListMoveRequest,
            ListMoveResponse,
            BlockingPopRequest,
            BlockingPopResponse,
            BlockingMoveRequest,
            // Set schemas
            SetAddRequest,
            SetAddResponse,
            SetRemoveRequest,
            SetRemoveResponse,
            SetMembersResponse,
            SetIsMemberRequest,
            SetIsMemberResponse,
            SetMIsMemberRequest,
            SetMIsMemberResponse,
            SetCardResponse,
            SetRandMemberQuery,
            SetRandMemberResponse,
            SetPopRequest,
            SetPopResponse,
            SetMoveRequest,
            SetMoveResponse,
            SetAlgebraRequest,
            SetAlgebraResponse,
            SetAlgebraStoreRequest,
            SetAlgebraStoreResponse,
            SetInterCardRequest,
            SetInterCardResponse,
            SetScanQuery,
            SetScanResponse,
            // Sorted Set schemas
            ScoredMemberDto,
            ZAddOptionsDto,
            ZAddRequest,
            ZAddResponse,
            ZAddIncrRequest,
            ZAddIncrResponse,
            ZRemRequest,
            ZRemResponse,
            ZMScoreRequest,
            ZMScoreResponse,
            ZScoreResponse,
            ZIncrByRequest,
            ZIncrByResponse,
            ZCardResponse,
            ScoreRangeDto,
            LexRangeDto,
            ZCountRequest,
            ZCountResponse,
            ZLexCountRequest,
            ZRankResponse,
            ZRangeQuery,
            ZRangeResponse,
            ZRangeByScoreRequest,
            ZRangeByLexRequest,
            ZRangeByLexResponse,
            ZRangeStoreRequest,
            ZRangeStoreResponse,
            ZRemRangeByRankRequest,
            ZRemRangeByScoreRequest,
            ZRemRangeByLexRequest,
            ZRemRangeResponse,
            ZPopQuery,
            ZPopResponse,
            ZBPopRequest,
            ZBPopResponse,
            ZMPopRequest,
            ZBMPopRequest,
            ZMPopResponse,
            ZRandMemberQuery,
            ZRandMemberResponse,
            ZAggregateDto,
            ZSetAlgebraOptionsDto,
            ZSetAlgebraRequest,
            ZSetAlgebraResponse,
            ZSetAlgebraStoreRequest,
            ZSetAlgebraStoreResponse,
            ZInterCardRequest,
            ZInterCardResponse,
            ZDiffRequest,
            ZDiffStoreRequest,
            ZScanQuery,
            ZScanResponse,
            // Stream schemas
            StreamEntry,
            StreamInfo,
            ConsumerGroupInfo,
            ConsumerInfo,
            PendingEntry,
            PendingSummary,
            StreamReadResult,
            ClaimResult,
            AutoClaimResult,
            StreamAddRequest,
            StreamAddResponse,
            StreamRangeQuery,
            StreamEntriesResponse,
            StreamLengthResponse,
            StreamDeleteRequest,
            StreamDeleteResponse,
            TrimStrategyParam,
            StreamTrimRequest,
            StreamTrimResponse,
            StreamInfoQuery,
            StreamIdPair,
            StreamReadRequest,
            StreamReadBlockingRequest,
            StreamSubscribeQuery,
            StreamGroupSubscribeQuery,
            StreamReadGroupRequest,
            StreamReadGroupBlockingRequest,
            StreamAckRequest,
            StreamAckResponse,
            PendingQuery,
            StreamClaimRequest,
            StreamAutoClaimRequest,
            ConsumerGroupCreateRequest,
            ConsumerGroupCreateResponse,
            ConsumerGroupSetIdRequest,
            ConsumerCreateRequest,
            ConsumerOperationResponse,
            StreamSetIdRequest,
            // Admin - Pool & Capabilities
            PoolStats,
            RedisCapabilities,
            ModuleCapabilities,
            FeatureCapabilities,
            // Admin - Server info (domain entities)
            ServerInfo,
            ServerTime,
            DbSizeResponse,
            LastSaveResponse,
            // Admin - Memory (domain entities + request schemas)
            MemoryStats,
            MemoryUsageRequest,
            MemoryUsage,
            MemoryDoctorResponse,
            MemoryPurgeResponse,
            // Admin - Database operations (domain entity + request/response schemas)
            FlushDbRequest,
            FlushResult,
            CopyKeyRequest,
            CopyKeyResponse,
            MoveKeyRequest,
            MoveKeyResponse,
            SwapDbRequest,
            SwapDbResponse,
            // Admin - Config
            ConfigGetRequest,
            ConfigGetResponse,
            ConfigSetRequest,
            ConfigSetResponse,
            ConfigRewriteResponse,
            ConfigResetStatResponse,
            // Admin - Persistence (domain entities + response schema)
            SaveResponse,
            BgSaveResult,
            BgRewriteAofResult,
            // Admin - Client (domain entity for ClientInfo)
            ClientInfo,
            ClientListResponse,
            ClientKillRequest,
            ClientKillResponse,
            ClientPauseRequest,
            ClientPauseResponse,
            ClientUnpauseResponse,
            ClientSetNameRequest,
            ClientSetNameResponse,
            ClientGetNameResponse,
            ClientIdResponse,
            // Admin - Slowlog
            SlowlogEntry,
            SlowlogGetRequest,
            SlowlogGetResponse,
            SlowlogLenResponse,
            SlowlogResetResponse,
            // Admin - Latency
            LatencyEvent,
            LatencyLatestResponse,
            LatencyHistoryRequest,
            LatencyHistoryResponse,
            LatencyDoctorResponse,
            LatencyResetRequest,
            LatencyResetResponse,
            // Admin - ACL
            AclListResponse,
            AclUsersResponse,
            AclWhoamiResponse,
            AclCatRequest,
            AclCatResponse,
            AclGenPassRequest,
            AclGenPassResponse,
            AclLogRequest,
            AclLogEntry,
            AclLogResponse,
            // JSON schemas (RedisJSON module)
            JsonSetRequest,
            JsonSetResponse,
            JsonGetParams,
            JsonGetResponse,
            JsonDelParams,
            JsonDelResponse,
            JsonMGetRequest,
            JsonMGetItem,
            JsonMGetResponse,
            JsonMSetItemRequest,
            JsonMSetRequest,
            JsonTypeParams,
            JsonTypeResponse,
            JsonStrLenParams,
            JsonStrLenResponse,
            JsonStrAppendRequest,
            JsonStrAppendResponse,
            JsonNumIncrByRequest,
            JsonNumMultByRequest,
            JsonNumResponse,
            JsonToggleParams,
            JsonToggleResponse,
            JsonClearParams,
            JsonClearResponse,
            JsonArrLenParams,
            JsonArrLenResponse,
            JsonArrAppendRequest,
            JsonArrAppendResponse,
            JsonArrIndexRequest,
            JsonArrIndexResponse,
            JsonArrInsertRequest,
            JsonArrInsertResponse,
            JsonArrPopRequest,
            JsonArrPopResponse,
            JsonArrTrimRequest,
            JsonArrTrimResponse,
            JsonObjLenParams,
            JsonObjLenResponse,
            JsonObjKeysParams,
            JsonObjKeysResponse,
            JsonDebugMemoryParams,
            JsonDebugMemoryResponse,
            JsonRespParams,
            JsonRespResponse,
        )
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

/// Security scheme modifier for OpenAPI
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "api_key",
                SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-Admin-Api-Key"))),
            );
        }
    }
}

/// Create OpenAPI routes with Swagger UI
pub fn openapi_routes() -> Router<AppState> {
    Router::new()
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_openapi_security_scheme() {
        let spec = ApiDoc::openapi();
        let components = spec.components.expect("components");
        assert!(components.security_schemes.contains_key("api_key"));
    }
}
